/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author jalberto.munoz
 */

public class Nominas extends javax.swing.JPanel {

    /**
     * Creates new form Nominas
     */
    public Nominas() {
        initComponents();
    }
    boolean comprueba = false;
    public void consultarUsuarios() {
        String datos = "";
        String vSQL = new String();
        int controla = 0;
        int i = 0;

        ConexionMySQL mysql = new ConexionMySQL();
        Connection cn = mysql.conectar();

        vSQL = "SELECT dni, nombre, apellidos, direccion, categoria, puesto, fecha_nacimiento, estado_civil, sueldo, horas_extra, telefono, estado_empresa, SS, IRPF FROM trabajador";

        try {

            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(vSQL);//devuelve el conjunto de datos.
            //ResultSet rs = mysqul.obtenerTable ("usuario");

            while (rs.next()) {

                datos = rs.getString("dni");
                if (datos.equalsIgnoreCase(JDNI.getText())) {
                    
                    JNOMBRE.setText(rs.getString("nombre"));
                    JAPELLIDOS.setText(rs.getString("apellidos"));
                    comprueba = true;
                    
                    break;
                }

            }
            if (!comprueba) {
                JOptionPane.showMessageDialog(null, "Ese número no corresponde con el de ningún trabajador");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }
    private PrincipalEmpresa b;
    List <ClaseReportCabecera> lista1;
    List <ClaseReportCalculos> lista2;

    public List<ClaseReportCabecera> getLista1() {
        return lista1;
    }

    public void setLista1(List<ClaseReportCabecera> lista1) {
        this.lista1 = lista1;
    }

    public List<ClaseReportCalculos> getLista2() {
        return lista2;
    }

    public void setLista2(List<ClaseReportCalculos> lista2) {
        this.lista2 = lista2;
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void setPrincipal(PrincipalEmpresa a) {
        this.b = a;
    }

    public void generarNomina() throws JRException {
        List<ClaseReportCabecera> cabeceraList = new LinkedList<ClaseReportCabecera>();
        ClaseReportCabecera R1 = new ClaseReportCabecera();
        R1.setApellidos(TOOL_TIP_TEXT_KEY);
        R1.setCIF(TOOL_TIP_TEXT_KEY);
        R1.setCategoria(TOOL_TIP_TEXT_KEY);
        R1.setCiudad(TOOL_TIP_TEXT_KEY);
        R1.setDireccion(TOOL_TIP_TEXT_KEY);
        R1.setDni(TOOL_TIP_TEXT_KEY);
        R1.setEstadoCivil(null);
        R1.setEstadoEmpresa(null);
        R1.setFechaNacimiento(TOOL_TIP_TEXT_KEY);
        R1.setHorasExtra(HEIGHT);
        R1.setIRPF(WIDTH);
        R1.setNombre(TOOL_TIP_TEXT_KEY);
        R1.setNombreEmpresa(TOOL_TIP_TEXT_KEY);
        R1.setNumeroSeguridadSocial(SOMEBITS);
        R1.setProvincia(TOOL_TIP_TEXT_KEY);
        R1.setRazonSocial(null);
        R1.setPuesto(TOOL_TIP_TEXT_KEY);
        R1.setRazonSocial(null);
        R1.setSueldo(WIDTH);
        R1.setTelefono(WIDTH);
        R1.setTelefonoEmpresa(TOOL_TIP_TEXT_KEY);
        cabeceraList.add(R1);

        List<ClaseReportCalculos> calculosList = new LinkedList<ClaseReportCalculos>();
        ClaseReportCalculos CRC1 = new ClaseReportCalculos();
        double calculoIT = R1.getSueldo();
        double calculoProrrata = R1.getSueldo() / 12;
        double calculoBCC = calculoIT * 0.047;
        double calculoDesempleo = calculoIT * 0.0155;
        double calculoProfesional = calculoIT * 0.001;
        double calculoIRPF = (R1.getSueldo() * R1.getIRPF()) / 100;
        double aDeducirSS = calculoBCC + calculoDesempleo + calculoProfesional;
        double aDeducir = aDeducirSS + calculoIRPF;
        double aPercibir = R1.getSueldo() - aDeducir;

        CRC1.setBaseIT(calculoIT);
        CRC1.setProrrata(calculoProrrata);
        CRC1.setCC(calculoBCC);
        CRC1.setDesempleo(calculoDesempleo);
        CRC1.setProfesional(calculoProfesional);
        CRC1.setPagarIRPF(calculoIRPF);
        CRC1.setTotalADeducir(aDeducir);
        CRC1.setTotalAPercibir(aPercibir);

        calculosList.add(CRC1);
        
        
        Nominas nom = new Nominas();
        nom.setLista1(cabeceraList);
        nom.setLista2(calculosList);
        
        try {
        JasperReport principal = JasperCompileManager
                .compileReport("C:/Users/jalberto.munoz/workspace/luna/JolideyQuelonea/ReportsQuelonea/PackageQ.jrxml");
//			
        Map<String, Object> parametrosPrincipal = new HashMap<String, Object>();

        parametrosPrincipal
                .put("SUBREPORT_DIR",
                        "C:/Users/jalberto.munoz/workspace/luna/JolideyQuelonea/ReportsQuelonea/");
        parametrosPrincipal.put("urlLogo",
                "C:/Users/jalberto.munoz/Downloads/Jolilogo.png");
        List<Nominas> listaInforme = new LinkedList<Nominas>();
        listaInforme.add((Nominas) nom);

        JRDataSource dataSource = new JRBeanCollectionDataSource(
                listaInforme);

        JasperPrint principalPrint = JasperFillManager.fillReport(
                principal, parametrosPrincipal, dataSource);
        JasperViewer.viewReport(principalPrint);
        JasperExportManager.exportReportToPdfFile(principalPrint,
                "Nomina.pdf");

    }
    catch (Exception e) {
			System.out.println(e.toString());
		}

    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JDNI = new javax.swing.JTextField();
        JNOMBRE = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        JAPELLIDOS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Comprueba = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("GENERAR NÓMINAS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("DNI");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("NOMBRE");

        JNOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNOMBREActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("GENERAR NÓMINA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("ATRÁS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("APELLIDOS");

        JAPELLIDOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAPELLIDOSActionPerformed(evt);
            }
        });

        jLabel4.setText("Introduzca el DNI para generar la nómina");

        Comprueba.setText("Aceptar");
        Comprueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompruebaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(JAPELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(JDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addComponent(Comprueba, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Comprueba, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JAPELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 82, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JNOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNOMBREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNOMBREActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        b.setCurrentPanel();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JAPELLIDOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAPELLIDOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JAPELLIDOSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CompruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompruebaActionPerformed
        consultarUsuarios();
    }//GEN-LAST:event_CompruebaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Comprueba;
    private javax.swing.JTextField JAPELLIDOS;
    private javax.swing.JTextField JDNI;
    private javax.swing.JTextField JNOMBRE;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
